### PR TITLE
Docs: Add Lenovo Zuk Z2 Plus

### PR DESCRIPTION
**Pull request by PptO07**
Maintainer Name: Pranav Temkar
Telegram Username: @PptOo7
Device: Lenovo Zuk Z2 Plus (z2_plus)
Device tree link: https://github.com/PptO07/device_zuk_z2_plus/tree/raven
Kernel Source Link: https://github.com/DerpGang/alchemy/tree/11-vndk
Vendor tree link: https://github.com/DerpGang/vendor_zuk_z2_plus/tree/11-vndk

Signed-off-by: Pranav Temkar <pranavtemkar@gmail.com>

### CODE REVIEW

**Comment by tompelitem** [comment]
@PptO07 No contribution tree 😬

**Comment by herobuxx** [comment]
@PptO07 Hi bro, try to cleanup your tree a bit, There is still some configs that didnt used.
Also, try to contribute some more on the tree :)
Anything else you're doing great job

**Comment by PptO07** [comment]
> @PptO07 Hi bro, try to cleanup your tree a bit, There is still some configs that didnt used.
> Also, try to contribute some more on the tree :)
> Anything else you're doing great job

sure thanks for the feedback

**Comment by herobuxx** [comment]
@herobuxx @Pulkit077 Me and @username502 have checked the tree, and it has lack conribution. But he PR-ed some commits on fw/b and other too. How u think?

**Comment by PptO07** [comment]
@herobuxx @tompelitem btw i had few cherry pick in tree in past can refer here:
https://github.com/PptO07/device_zuk_z2_plus/commit/2871d618e21934dbff2e58b8051a4fa7d3f28eb7
https://github.com/PptO07/device_zuk_z2_plus/commit/77de678d72b48152ca6e22097f0c4b1e9b243338
https://github.com/PptO07/device_zuk_z2_plus/commit/555fb84a2856957f1dfd55b609d7cb005e3bb45f
https://github.com/PptO07/device_zuk_z2_plus/commit/7fffbdea333003098f7df3af7ce6d72fd4b7fd28
https://github.com/PptO07/device_zuk_z2_plus/commit/4caf7468d585b05bd3896252bbb60693ee44dfb3
https://github.com/PptO07/device_zuk_z2_plus/commit/5b04fdcf9cf7acce05f50c1c1107df270846cf79

these in vendor
https://github.com/DerpGang/vendor_zuk_z2_plus/commit/f6afad491348914917c768b709ca4cce8f6775e6
https://github.com/DerpGang/vendor_zuk_z2_plus/commit/2d31858370b560323e700e35a7e675153d6d427f

and many more just these are a bit old and dmitri keeps pushing stable stuffs in tree so they are not seen in recent commit history

i agree conquer was easy to build was just a bringup commit, will definitely pick more stable stuffs in near future

**Pull request merged**
