### PR TITLE
Applying for Official (X00TD)

### PR DESCRIPTION
**Pull request by harshhaareddy**

### CODE REVIEW

**Comment by Pulkit077** [comment]
Update `maintainers.md` as well and force push to a single commit

**Comment by herobuxx** [comment]
Where is Devixe tree link? Also attach username

**Comment by harshhaareddy** [comment]
done sir

**Comment by herobuxx** [comment]
@harshhaareddy Please provide us device tree link. So then we can see are you eligible for the maintainership

**Comment by harshhaareddy** [comment]
Device tree : https://github.com/harshhaareddy/device_asus_X00TD.git

Vendor tree : https://github.com/harshhaareddy/proprietary_vendor_asus.git

Common tree : https://github.com/harshhaareddy/device_asus_sdm660-common.git

**Pull request closed without merging**
